; PlatformIO Project Configuration File


[env:ttgo-lora32-v21]
platform = espressif32
board = ttgo-lora32-v21
framework = arduino

; Dependencies
lib_deps =
    knolleary/PubSubClient @ ^2.8
; [env:esp32dev]
; platform = espressif32
; board = esp32dev
; ;board = esp32doit-devkit-v1
; framework = arduino
; framework = espidf

; Custom Serial Monitor port
; monitor_port = /dev/ttyUSB0

; Custom Serial Monitor speed (baud rate)
monitor_speed = 115200
monitor_dtr = 0
monitor_rts = 0