[env:ttgo-lora32-v21]
platform = espressif32
board = ttgo-lora32-v21
framework = arduino

build_flags =
    -D RADIOLIB_LORAWAN_EU868

lib_deps =
    jgromes/RadioLib @ ^6.4.0
    knolleary/PubSubClient @ ^2.8
    Teleplot

monitor_speed = 115200
monitor_dtr = 0
monitor_rts = 0