; Workplace Air Quality Monitoring System
; PlatformIO Project Configuration File

[env:heltec_wifi_lora_32_V3]
platform = espressif32
board = heltec_wifi_lora_32_V3
framework = arduino

monitor_speed = 115200


lib_ldf_mode = deep+
build_flags =
	-I include	   					 ; Adding project's `include/` to the compiler include path
	-D RADIOLIB_LORAWAN_REGION_EU868 ; LoRaWAN region for RadioLib

lib_deps = 
	sensirion/Sensirion Core@^0.7.3
	sensirion/Sensirion I2C SCD4x@^1.1.0
	ropg/Heltec_ESP32_LoRa_v3
    ropg/LoRaWAN_ESP32
    RadioLib