[env:heltec_wifi_lora_32_V3]
platform = espressif32
board = heltec_wifi_lora_32_V3
framework = arduino
monitor_speed = 115200
lib_deps = 
    sensirion/Sensirion Core @ ^0.7.3
    sensirion/Sensirion I2C SCD4x @ ^1.1.0
    ropg/Heltec_ESP32_LoRa_v3
    ropg/LoRaWAN_ESP32
    jgromes/RadioLib@^7.2.0
    ropg/Heltec_ESP32_LoRa_v3
    https://github.com/ropg/LoRaWAN_ESP32.git
    kosme/arduinoFFT@^2.0.2
    knolleary/PubSubClient@^2.8
    sensirion/Sensirion I2C SCD4x@^0.4.0

build_flags =
	-I include	   					 ; Adding project's `include/` to the compiler include path
	-D RADIOLIB_LORAWAN_REGION_EU868 ; LoRaWAN region for RadioLib
    -D HELTEC_UNOFFICIAL_NO_DEFS